apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ta-nupic
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: ta-nupic
        k8s-app: ta-nupic
    spec:
      containers:
      - name: anomaly
        image: gcr.io/arkavidia-178003/ta-nupic:2.0
        env:
        - name: GAUGE1
          value: "anomaly_score_test"
        - name: GAUGE2
          value: "raw_score_test"
        - name: GAUGE3
          value: "convoluted_anomaly_score_test"
        - name: EXPR
          value: "sum by (container_name) (rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\",container_name=\"ctfd\"}[1m]))"
        - name: INPUT_MIN
          value: "0.0"
        - name: INPUT_MAX
          value: "0.3"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: ta-nupic
  name: ta-nupic
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    k8s-app: ta-nupic
